[webservers]
# Format: [VM_NAME] ansible_host=[INTERNAL_IP]
hc-test-vm ansible_host=10.0.2.2

[webservers:vars]
# The ProxyCommand creates the secure IAP tunnel
[webservers:vars]
ansible_user=gutierrezjd97_gmail_com
ansible_ssh_private_key_file=~/.ssh/google_compute_engine
ansible_ssh_common_args='-o ProxyCommand="/usr/bin/gcloud compute start-iap-tunnel hc-test-vm 22 --listen-on-stdin --project=healthconnect-project-500381 --zone=us-central1-a --quiet" -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
