---
- name: Deploy HealthConnect Portal
  hosts: webservers
  become: yes
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Deploy Secure Homepage
      copy:
        content: "<h1>HealthConnect Secure Portal</h1><p>Managed via Ansible OS-Login</p>"
        dest: /var/www/html/index.html